### ISSUE TITLE
module/todo: checked icon and color not worked

### ISSUE THREAD

**Issue by scbizu** [wtfutil/wtf#616]
Hi, there. You guys has made a really cool tool for me ! Thank you !

## What's broken?

I run into an unexpected condition when I setup my todo module. I write this following todo config into my `config.yml` at first.
```yaml
    todolist:
      type: todo
      checkedIcon: "x"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
```

But , when I use `space` to finish one of my todos , its color still stay in white, and not turn into gray as I expected . Then, I tried to restore my config to your sample config(change the `checkedIcon: "x"` to `checkedIcon: "X"`), but when I open my todo again, the icon is still 'x' not 'X' (I delete my todo.yml before I open todo again) , and the color is still not work for me(stay in white). Do I miss something ?

### edited todo module config

```yaml
    todolist:
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 3
        height: 2
        width: 5
      refreshInterval: 60
      title: "📝Todos"
```

### Screenshoot

![image](https://user-images.githubusercontent.com/8732481/64451087-08e19d00-d116-11e9-9983-cbda350740ae.png)

**Comment by senorprogrammer** [comment]
Yep, definitely a bug. Probably an issue with recently-made internal config changes. Should be fixed in the next release.

**Comment by senorprogrammer** [comment]
Btw, thank you for reporting this.

**Comment by scbizu** [comment]
OK , leave me a message if you guys need me 🙈

**Comment by Seanstoppable** [comment]
I am not actually sure if it was every configurable on the module level. Looks like currently it is a global config like:

```
wtf:
  sigils:
    checkbox:
      checked: 'X'
```

Unsure if we want to configure this at the module level as well, but if so, I can make all the settings in `NewCommonSettingsFromModule` check the module config before it checks global configs.

A bunch of color related stuff doesn't seem to be overridable at the module level, and I've fixed this in #620

**Comment by senorprogrammer** [comment]
I have a PR on the way that should address this issue.

**Comment by Seanstoppable** [comment]
Color should be improved on `master` now.

**Comment by senorprogrammer** [comment]
Works nicely.

**Comment by scbizu** [comment]
@Seanstoppable LGTM . But the checked icon is still not work .

**Comment by Seanstoppable** [comment]
Yeah, my PR focused on coloring, to make it consistent across modules. Open question on if the X should be configurable per module that uses it (which may just be the TODO module), or if it makes sense for it to be controlled globally (which is the level at which it is controlled today). It is not clear to me if this is a logic problem, or a documentation problem.

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/674

**Comment by scbizu** [comment]
LGTM
